### ISSUE TITLE
Potential bug in class LogTKESpectrumL2Distance

### ISSUE THREAD

**Issue by anthonyzhou-1** [martenlienen/generative-turbulence#1]
Hi,

First of all, thank you for the well-documented code, it has been super helpful and the work itself is great. I'm not super familiar with TKE, but from what I can tell from the paper/code, I was wondering if there was a bug [here](https://github.com/martenlienen/generative-turbulence/blob/161595dabecb76264b31c3bb85ba4230c6030ce8/turbdiff/models/metrics.py#L373) ?
Should this:
`(log_tke_a[:, None] - log_tke_b[None]) ** 2,`
be this?
`(log_tke_a[:, None] - log_tke_b[:, None]) ** 2,` 

Again, not super familiar with TKE, but just wanted to ask since when calling:
`D, _, _, _ = logTKEcriterion(data, data, mean_data)`
I unfortunately don't get zero distance.
 Thanks!

**Comment by martenlienen** [comment]
Hey,
great to hear that the code is helpful to you! This line computes the distance between any pair of snapshots, so if `u_a` and contains 5 snapshots and `u_b` contains 7, the output should be a 5x7 distance matrix where `D[i, j]` is the distance between `u_a[i]` and `u_b[j]`. That also explains, why your test does not give you a zero matrix. You probably have multiple snapshots in your data that are not all the same. However, `D[i, i]`, i.e. the diagonal of `D`, should be zero.

Best,
Marten

**Comment by anthonyzhou-1** [comment]
That makes sense, thank you! Appreciate the quick reply as well and best of luck on your future works.
